accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'), # サインアップページ
]

bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'), #一覧ページのビュー
    path('<int:pk>/', views.DetailView.as_view(),name='detail'), # 投稿詳細ページ
    path('create/',views.CreateView.as_view(),name='create'),#新規投稿ページ
    path('<int:pk>/update/',views.UpdateView.as_view(),name="update"),#投稿編集ページ
    path('<int:pk>/delete/',views.DeleteView.as_view(),name='delete'),#投稿削除ページ
    path('search/', views.search, name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from bbs.views import custom_permission_denied_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbs/',include('bbs.urls')),
    path('',RedirectView.as_view(url = '/bbs/')),
    path('accounts/',include('accounts.urls')),# accounts/以下のルーティングはaccounts.urls.pyに任せる
    path('accounts/', include('django.contrib.auth.urls')),     # ユーザー認証用のビューを呼び出す
]

handler403 = 'bbs.views.custom_permission_denied_view'

accounts/models.py
from django.db import models

# Create your models here.

bbs/models.py
from django.db import models
from django.contrib.auth.models import User # Userモデルをインポート
from django.urls import reverse #reverse関数をインポート

class Article(models.Model):#継承元を()の中に書く
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # 投稿完了したあとのリダイレクト処理！
    # モデルのデータを保存した後、勝手に実行してくれる
    def get_absolute_url(self):
        return reverse("bbs:detail", kwargs={"pk": self.pk})
    
    
    def __str__(self):
        return self.content
    
    # self.contentじゃなくてもよい。管理画面でどう表示したいかによってカスタマイズする。今回は投稿内容のみ

bbs/forms.py
from django import forms

class SerchForm(forms.Form):
    words = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control me-2',
            'placeholder' : 'キーワードを入力',
        })
    )

accounts/views.py
# from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm #ユーザー登録用のフォームクラスをインポート
from django.urls import reverse_lazy
from django.views import generic

#SignUpViewクラスを作成
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login') #サインアップ成功時、ログインページのURLにリダイレクト
    template_name = 'accounts/signup.html'

bbs/views.py
from django.shortcuts import render
from django.views import generic #汎用ビューのインポート
from .models import Article #models.pyのArticleクラスをインポート
from django.urls import reverse_lazy #reverse_lazyクラスをインポート
from .forms import SerchForm
from django.contrib.auth.mixins import LoginRequiredMixin #LoginRequiredMixin
from django.core.exceptions import PermissionDenied #PermissionDeniedをインポート

# IndexViewクラスを作成
class IndexView(generic.ListView):
    model = Article #Articleモデルを使用
    template_name = 'bbs/index.html' #使用するテンプレート名を指定（Articleも自動で渡す）
    
# DetailViewクラスを作成
class DetailView(generic.DetailView):
    model = Article
    template_name = 'bbs/detail.html'
    
# CreateViewクラスを作成
# 新規投稿はログインしているユーザーのみ
class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Article
    template_name = 'bbs/create.html'
    fields = ['content']
    
    #格納する値をチェック
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)
     
    #どのモデルフィールドをフォームとして扱うかを定義される。
    # モデルに定義されているすべてのフィールドが自動的にフォームとして生成される
    
# UpdateViewクラスを作成
# 投稿編集はログインしているユーザーのみ
class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Article
    template_name = 'bbs/create.html'
    fields = ['content'] #項目をcontentのみに変更
# 編集も投稿ページと同じページで行う
# UpdateView↓
# 既存のオブジェクトを編集するフォームを用意し、変更を保存」する汎用ビュー

    #dispatchメソッドで権限チェックを追加
    def dispatch(self, request, *args, **kwargs):
        #編集対象の投稿オブジェクトを取得
        obj = self.get_object()
        #投稿者と現在のユーザーが一致しない場合は403エラーを発生
        if obj.author != self.request.user:
            raise PermissionDenied('編集権限がありません')
        #親クラスのdispatchを呼び出して通常の処理を継続
        return super(UpdateView, self).dispatch(request, *args, **kwargs)
    

# DeleteViewクラスを作成
# 投稿削除はログインしているユーザーのみ
class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Article
    template_name = 'bbs/delete.html'
    success_url = reverse_lazy('bbs:index')
# まだデータが受け取れてないとreverseだとエラーを吐いてしまうことがある。
# その為、今回はreverse_lazyを使用

    def dispatch(self, request, *args, **kwargs):
        #削除対象の投稿オブジェクトを取得
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('削除権限が有りません')
        return super(DeleteView,self).dispatch(request, *args, **kwargs)

def search(request):
    articles = None
    searchform = SerchForm(request.GET)
    
    if searchform.is_valid():
        query = searchform.cleaned_data['words']
        articles = Article.objects.filter(content__icontains = query)
        return render(request, 'bbs/results.html',{'articles':articles, 'searchform':searchform})
    
    
#カスタム403のビューを定義
def custom_permission_denied_view(request, exception):
    return render(request,'403.html',{'error_message': str(exception)}, status=403)

templates/accounts/signup.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1>Djangoで作るサインアップ機能</h1>
<section>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form%}
        {% bootstrap_button button_type="submit" content="サインアップ" size="md" %}
    </form>
</section>
{% endblock %}

templates/base.html
{% load django_bootstrap5 %}
{% comment %} django_bootstrap5のテンプレートタグ読み込み {% endcomment %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BBS Project{% block title %}{% endblock %}</title>
    <style>
        body {
            background-color: pink;
            color: brown;
        }
        .container {
            background-color: #efefef;
        }
    </style>
    {% bootstrap_css %}
    {% comment %} Bootstrapのcssの読み込み {% endcomment %}
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'bbs:index' %}">BBS Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <span class="nav-link active">{{ user }}でログイン中</span>
                    {% endif %}
                </li>
                <li class="nav-item">
                     {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="nav-link active">ログアウト</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="nav-link active">ログイン</a>
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" method="get" action="{% url 'bbs:search'%}">
                {#inputタグを消して#}
                {{ searchform.words }}
                {% comment %} <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> {% endcomment %}
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
    <div class = "container py-2 mt-5">
        {% block content %}
        {% comment %}各ページのコンテンツが挿入される{% endcomment %}
        {% endblock %}
    </div>
    {% bootstrap_javascript %}
    {% comment %} bootstrapのjsの読み込み {% endcomment %}
</body>
</html>

templates/bbs/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title%}{{object|yesno:'-投稿編集,-新規作成'}}{% endblock %}

{% block content %}

<h1>投稿の{{object|yesno:'編集,新規作成'}}</h1>

<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form%} {# すべての項目を表示 #}
    {% bootstrap_button button_type="submit" content=object|yesno:'更新,作成' size="md"%}
</form>
<div class="mt-3">
    <a href="{% url 'bbs:index'%}">{% bootstrap_button button_type="submit" button_class="btn-secondary" content="一覧ページへ戻る" size="md" %}</a>
</div>
{% endblock%}

{% comment %} 

{% csrf_token %}
↑は本人になりすました不正なリクエストを送られたときの
対策に使用されるテンプレートタグ CSRF対策としてCSRFトークンを使用する。
フォームをレンダリングする際に、
隠し入力フィールドでDjangoが生成した一意のトークンが自動的に埋め込まれる仕組み。

{{ form.as_p }}フォームが自動生成されるインスタンス。便利だね。

{{object|yesno:'文字列１,文字列２'}}:
Djangoのテンプレートフィルターyesnoを使用。
object値がTrueなら1つ目の文字列、Falseなら2つ目の文字列を表示するよ！
今回の動き：
【新規】
object＝新規（新しいインスタンス）で
データベースに保存されていないよ
object=存在しない　でFalseになるので「新規」が表示。
ボタンは作成になるよ
【編集】
object=既存のインスタンスで
object=存在するなのでTrueになり「編集」が表示。
ボタンも更新になるよ
{% endcomment %}

templates/bbs/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}-投稿削除{% endblock %}

{% block content %}
<h1>投稿の削除</h1>
<p>"{{ object.id }}"の投稿を削除しますか？</p>
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" button_class="btn-danger" content="削除" size="md" %}
</form>
<div class="mt-3">
    <a href="{% url 'bbs:index' %}">{% bootstrap_button button_type="submit" button_class="btn-secondary" content="一覧ページへ戻る" size="md" %}</a>
</div>
{% endblock  %}

templates/bbs/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}投稿詳細ページ{% endblock %}

{% block content %}
{% comment %} articleじゃなくてobjectでも使えるらしい {% endcomment %}
    <h1>{{ article.id }}の投稿詳細ページ</h1>
    <div class="card bg-light shadow-sm mt-3">
        <div class="card-body">
            <p>{{ article.author }}：{{ article.created_at }}</p>
            {#} 更新後の日時が入る↓ {#}
            <p>最終更新:{{object.update_at}}</p>
            <p>{{ article.content }}</p>
            {#} pkは今回は投稿の主キー（1，2，3のような数字だったね） {#}
            <p><a href="{% url "bbs:update" object.pk%}">{% bootstrap_button button_type="submit" button_class="btn-success" content="編集" size="md" %}</a></p>
            <p><a href="{% url "bbs:delete" object.pk%}">{% bootstrap_button button_type="submit" button_class="btn-danger" content="削除" size="md" %}</a></p>
        </div>
    </div>
    <p><a href="{% url 'bbs:index' %}">{% bootstrap_button button_type="submit" button_class="btn-secondary" content="一覧ページに戻る" size="md"%}</a></p>
{% endblock  %}

templates/bbs/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
    <h1>CRUDアプリを作ってみよう</h1>
        {% for article in object_list %}
            <div class='card bg-light shadow-sm mt-3'>
                <div class="card-body">
                    <p>{{article.id}} : {{article.author}} : {{article.created_at}}</p>
                    <p><a href="{% url 'bbs:detail' article.id %}">{{ article.content}}</a></p>
                </div>
            </div>
        {% endfor %}
        {% comment %}ログインしている場合{% endcomment %}
        {% if user.is_authenticated %}
            <div class="mt-3">
                <a href="{% url 'bbs:create' %}">{% bootstrap_button button_type="submit" content="新規投稿" size="md" %}</a>
            </div>
        {% endif %}
{% endblock content %}

templates/bbs/results.html
{% extends 'base.html' %}
{% block content %}
  <h1>検索結果：</h1>
  {% if articles %}
    {% for article in articles %}
      <div class="card bg-light shadow-sm mt-3">
	        <div class="card-body">
          <p>{{ article.id }}:{{ article.author }}:{{ article.created_at }}</p>
          <p><a href="{% url 'bbs:detail' article.id %}">{{ article.content }}</a></p>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>"{{ searchform.words.value }}"に一致する投稿はありません。</p>
  {% endif %}
{% endblock %}